# feat estimation with different batch sizes and estimation samples
# python classattack_feat_one_shot.py name=feat_one_shot_b01_est500 attack=clsattack case.server.name=class_malicious_parameters case/data=ImageNet case.user.provide_labels=True base_dir=/cmlscratch/ywen/breaching/breaching/outputs num_trials=100 +num_to_est=500 +batch_size=1
# python classattack_feat_one_shot.py name=feat_one_shot_b02_est500 attack=clsattack case.server.name=class_malicious_parameters case/data=ImageNet case.user.provide_labels=True base_dir=/cmlscratch/ywen/breaching/breaching/outputs num_trials=100 +num_to_est=500 +batch_size=2
# python classattack_feat_one_shot.py name=feat_one_shot_b04_est500 attack=clsattack case.server.name=class_malicious_parameters case/data=ImageNet case.user.provide_labels=True base_dir=/cmlscratch/ywen/breaching/breaching/outputs num_trials=100 +num_to_est=500 +batch_size=4
python classattack_feat_one_shot.py name=feat_one_shot_b08_est500 attack=clsattack case.server.name=class_malicious_parameters case/data=ImageNet case.user.provide_labels=True base_dir=/cmlscratch/ywen/breaching/breaching/outputs num_trials=100 +num_to_est=500 +batch_size=8
python classattack_feat_one_shot.py name=feat_one_shot_b16_est500 attack=clsattack case.server.name=class_malicious_parameters case/data=ImageNet case.user.provide_labels=True base_dir=/cmlscratch/ywen/breaching/breaching/outputs num_trials=100 +num_to_est=500 +batch_size=16

# python classattack_feat_one_shot.py name=feat_one_shot_b01_est700 attack=clsattack case.server.name=class_malicious_parameters case/data=ImageNet case.user.provide_labels=True base_dir=/cmlscratch/ywen/breaching/breaching/outputs num_trials=100 +num_to_est=700 +batch_size=1
# python classattack_feat_one_shot.py name=feat_one_shot_b02_est700 attack=clsattack case.server.name=class_malicious_parameters case/data=ImageNet case.user.provide_labels=True base_dir=/cmlscratch/ywen/breaching/breaching/outputs num_trials=100 +num_to_est=700 +batch_size=2
python classattack_feat_one_shot.py name=feat_one_shot_b04_est700 attack=clsattack case.server.name=class_malicious_parameters case/data=ImageNet case.user.provide_labels=True base_dir=/cmlscratch/ywen/breaching/breaching/outputs num_trials=100 +num_to_est=700 +batch_size=4
python classattack_feat_one_shot.py name=feat_one_shot_b08_est700 attack=clsattack case.server.name=class_malicious_parameters case/data=ImageNet case.user.provide_labels=True base_dir=/cmlscratch/ywen/breaching/breaching/outputs num_trials=100 +num_to_est=700 +batch_size=8
python classattack_feat_one_shot.py name=feat_one_shot_b16_est700 attack=clsattack case.server.name=class_malicious_parameters case/data=ImageNet case.user.provide_labels=True base_dir=/cmlscratch/ywen/breaching/breaching/outputs num_trials=100 +num_to_est=700 +batch_size=16

# python classattack_feat_one_shot.py name=feat_one_shot_b01_est900 attack=clsattack case.server.name=class_malicious_parameters case/data=ImageNet case.user.provide_labels=True base_dir=/cmlscratch/ywen/breaching/breaching/outputs num_trials=100 +num_to_est=900 +batch_size=1
python classattack_feat_one_shot.py name=feat_one_shot_b02_est900 attack=clsattack case.server.name=class_malicious_parameters case/data=ImageNet case.user.provide_labels=True base_dir=/cmlscratch/ywen/breaching/breaching/outputs num_trials=100 +num_to_est=900 +batch_size=2
python classattack_feat_one_shot.py name=feat_one_shot_b04_est900 attack=clsattack case.server.name=class_malicious_parameters case/data=ImageNet case.user.provide_labels=True base_dir=/cmlscratch/ywen/breaching/breaching/outputs num_trials=100 +num_to_est=900 +batch_size=4
python classattack_feat_one_shot.py name=feat_one_shot_b08_est900 attack=clsattack case.server.name=class_malicious_parameters case/data=ImageNet case.user.provide_labels=True base_dir=/cmlscratch/ywen/breaching/breaching/outputs num_trials=100 +num_to_est=900 +batch_size=8
python classattack_feat_one_shot.py name=feat_one_shot_b16_est900 attack=clsattack case.server.name=class_malicious_parameters case/data=ImageNet case.user.provide_labels=True base_dir=/cmlscratch/ywen/breaching/breaching/outputs num_trials=100 +num_to_est=900 +batch_size=16