
# Run binary attack / cls collision in a variety of settings:
# Reduced trials from here on out!
# 1) random batches
python classattack_breaches.py name=clsattack_optaverage_b01_rand_fullImageNet case.user.user_idx=0 case.user.num_data_points=1 attack=clsattack case.server.name=class_malicious_parameters case/data=ImageNet case.user.provide_labels=True case.data.partition=random case.data.default_clients=100 base_dir=/cmlscratch/jonas0/breaching/outputs save_reconstruction=True +opt_on_avg_grad=True num_trials=50
python classattack_breaches.py name=clsattack_optaverage_b32_rand_fullImageNet case.user.user_idx=0 case.user.num_data_points=32 attack=clsattack case.server.name=class_malicious_parameters case/data=ImageNet case.user.provide_labels=True case.data.partition=random case.data.default_clients=100 base_dir=/cmlscratch/jonas0/breaching/outputs save_reconstruction=True +opt_on_avg_grad=True num_trials=50
python classattack_breaches.py name=clsattack_optaverage_b64_rand_fullImageNet case.user.user_idx=0 case.user.num_data_points=64 attack=clsattack case.server.name=class_malicious_parameters case/data=ImageNet case.user.provide_labels=True case.data.partition=random case.data.default_clients=100 base_dir=/cmlscratch/jonas0/breaching/outputs save_reconstruction=True +opt_on_avg_grad=True num_trials=50
python classattack_breaches.py name=clsattack_optaverage_b128_rand_fullImageNet case.user.user_idx=0 case.user.num_data_points=128 attack=clsattack case.server.name=class_malicious_parameters case/data=ImageNet case.user.provide_labels=True case.data.partition=random case.data.default_clients=100 base_dir=/cmlscratch/jonas0/breaching/outputs save_reconstruction=True +opt_on_avg_grad=True num_trials=50
python classattack_breaches.py name=clsattack_optaverage_b256_rand_fullImageNet case.user.user_idx=0 case.user.num_data_points=256 attack=clsattack case.server.name=class_malicious_parameters case/data=ImageNet case.user.provide_labels=True case.data.partition=random case.data.default_clients=100 base_dir=/cmlscratch/jonas0/breaching/outputs save_reconstruction=True +opt_on_avg_grad=True num_trials=50
python classattack_breaches.py name=clsattack_optaverage_b500_rand_fullImageNet case.user.user_idx=0 case.user.num_data_points=500 attack=clsattack case.server.name=class_malicious_parameters case/data=ImageNet case.user.provide_labels=True case.data.partition=random case.data.default_clients=100 base_dir=/cmlscratch/jonas0/breaching/outputs save_reconstruction=True +opt_on_avg_grad=True num_trials=50

# 2) batches with a single class (the worst case for the binary attack)
python classattack_breaches.py name=clsattack_optaverage_b1_unique_fullImageNet case.user.user_idx=0 case.user.num_data_points=1 attack=clsattack case.server.name=class_malicious_parameters case/data=ImageNet case.user.provide_labels=True case.data.partition=unique-class case.data.default_clients=100 base_dir=/cmlscratch/jonas0/breaching/outputs save_reconstruction=True +opt_on_avg_grad=True num_trials=50
python classattack_breaches.py name=clsattack_optaverage_b4_unique_fullImageNet case.user.user_idx=0 case.user.num_data_points=4 attack=clsattack case.server.name=class_malicious_parameters case/data=ImageNet case.user.provide_labels=True case.data.partition=unique-class case.data.default_clients=100 base_dir=/cmlscratch/jonas0/breaching/outputs save_reconstruction=True +opt_on_avg_grad=True num_trials=50
python classattack_breaches.py name=clsattack_optaverage_b8_unique_fullImageNet case.user.user_idx=0 case.user.num_data_points=8 attack=clsattack case.server.name=class_malicious_parameters case/data=ImageNet case.user.provide_labels=True case.data.partition=unique-class case.data.default_clients=100 base_dir=/cmlscratch/jonas0/breaching/outputs save_reconstruction=True +opt_on_avg_grad=True num_trials=50
python classattack_breaches.py name=clsattack_optaverage_b16_unique_fullImageNet case.user.user_idx=0 case.user.num_data_points=16 attack=clsattack case.server.name=class_malicious_parameters case/data=ImageNet case.user.provide_labels=True case.data.partition=unique-class case.data.default_clients=100 base_dir=/cmlscratch/jonas0/breaching/outputs save_reconstruction=True +opt_on_avg_grad=True num_trials=50
python classattack_breaches.py name=clsattack_optaverage_b32_unique_fullImageNet case.user.user_idx=0 case.user.num_data_points=32 attack=clsattack case.server.name=class_malicious_parameters case/data=ImageNet case.user.provide_labels=True case.data.partition=unique-class case.data.default_clients=100 base_dir=/cmlscratch/jonas0/breaching/outputs save_reconstruction=True +opt_on_avg_grad=True num_trials=50
python classattack_breaches.py name=clsattack_optaverage_b50_unique_fullImageNet case.user.user_idx=0 case.user.num_data_points=50 attack=clsattack case.server.name=class_malicious_parameters case/data=ImageNet case.user.provide_labels=True case.data.partition=unique-class case.data.default_clients=100 base_dir=/cmlscratch/jonas0/breaching/outputs save_reconstruction=True +opt_on_avg_grad=True num_trials=50

# 2) batches with mixup (the medium case for the clsattack)
python classattack_breaches.py name=clsattack_optaverage_b01_mixup_fullImageNet case.user.user_idx=0 case.user.num_data_points=1 attack=clsattack case.server.name=class_malicious_parameters case/data=ImageNet case.user.provide_labels=True case.data.partition=mixup case.data.default_clients=100 base_dir=/cmlscratch/jonas0/breaching/outputs save_reconstruction=True +opt_on_avg_grad=True num_trials=50
python classattack_breaches.py name=clsattack_optaverage_b16_mixup_fullImageNet case.user.user_idx=0 case.user.num_data_points=16 attack=clsattack case.server.name=class_malicious_parameters case/data=ImageNet case.user.provide_labels=True case.data.partition=mixup case.data.default_clients=100 base_dir=/cmlscratch/jonas0/breaching/outputs save_reconstruction=True +opt_on_avg_grad=True num_trials=50
python classattack_breaches.py name=clsattack_optaverage_b32_mixup_fullImageNet case.user.user_idx=0 case.user.num_data_points=32 attack=clsattack case.server.name=class_malicious_parameters case/data=ImageNet case.user.provide_labels=True case.data.partition=mixup case.data.default_clients=100 base_dir=/cmlscratch/jonas0/breaching/outputs save_reconstruction=True +opt_on_avg_grad=True num_trials=50
python classattack_breaches.py name=clsattack_optaverage_b64_mixup_fullImageNet case.user.user_idx=0 case.user.num_data_points=64 attack=clsattack case.server.name=class_malicious_parameters case/data=ImageNet case.user.provide_labels=True case.data.partition=mixup case.data.default_clients=100 base_dir=/cmlscratch/jonas0/breaching/outputs save_reconstruction=True +opt_on_avg_grad=True num_trials=50
python classattack_breaches.py name=clsattack_optaverage_b128_mixup_fullImageNet case.user.user_idx=0 case.user.num_data_points=128 attack=clsattack case.server.name=class_malicious_parameters case/data=ImageNet case.user.provide_labels=True case.data.partition=mixup case.data.default_clients=100 base_dir=/cmlscratch/jonas0/breaching/outputs save_reconstruction=True +opt_on_avg_grad=True num_trials=50
python classattack_breaches.py name=clsattack_optaverage_b256_mixup_fullImageNet case.user.user_idx=0 case.user.num_data_points=256 attack=clsattack case.server.name=class_malicious_parameters case/data=ImageNet case.user.provide_labels=True case.data.partition=mixup case.data.default_clients=100 base_dir=/cmlscratch/jonas0/breaching/outputs save_reconstruction=True +opt_on_avg_grad=True num_trials=50
